Maghion/fundfairy

- app/Http/Controllers/DonationController.php
- resources/views/donation/create.blade.php
- resources/views/donation/index.blade.php
- routes/web.php
Go to /donation to see all donations, /donation/create to see donation form, and /donation/{id} to see individual donation
> Added DonationController, donation create and index views

- app/Http/Controllers/BusinessReviewController.php
- resources/views/business-review/create.blade.php
- resources/views/business-review/index.blade.php
- routes/web.php
Visit /business-review-> to see a list of business reviews, /business-review/create-> will let you add a new business review, and /business-review/{id}-> to view details of a specific business review by ID
> Created Business-ReviewCotronller with Create & Index views

- app/Http/Controllers/TestimonialController.php
- resources/views/testimonial/create.blade.php
- resources/views/testimonial/index.blade.php
- routes/web.php
/testimonial, /testimonial/create, testimonial/{1}
> Created TestimonialController with Create & Index views

- resources/views/components/fund-fairy-header.blade.php
- resources/views/components/fund-fairy-nav-link.blade.php
adjusted the color of the hovering on the elements in the navbar (light gray hover, if selected slightly darker yellow hover) and added mobile dropdown formatting to navbar
> Touched up Nav-link styles and added mobile formatting to nav bar

- database/migrations/2025_03_07_162116_create_donations_table.php
Created create_donations_table migration and fixed, needs to be migrated
> Created create_donations_table migration

- app/Http/Controllers/UserController.php
- app/Models/User.php
- resources/views/users/index.blade.php
- routes/web.php
Visit /users to see the test user's email address. The link to show an individual user isn't implemented.
> User model and more

- resources/views/components/fund-fairy-header.blade.php
View any page to see mobile menu button
> Fixed mobile hamburger button padding

- app/Http/Controllers/DonationController.php
- app/Models/Donation.php
- app/Models/User.php
- resources/views/donation/create.blade.php
- resources/views/donation/index.blade.php
- resources/views/donation/show.blade.php
Made Donation Model, updated create and index, and DonationController to show/create donation _information_ from database. 
Go to /donation to see updated donations list, /donations/create to create, and /donations/{id} to see singular
> Created Donation Model and updates

- resources/views/businesses/show.blade.php
Added Business Description and Featured
> Adjustments to Business Show.Blade file.

- app/Http/Controllers/AboutController.php
- app/Http/Controllers/NewsletterController.php
- app/Models/Newsletter.php
- resources/views/about/index.blade.php
- resources/views/components/fund-fairy-footer.blade.php
- resources/views/newsletter/index.blade.php
- routes/web.php
updated footer links about us and subscribe link
> About and Newsletter controller and blade files

- resources/views/components/fund-fairy-donation-card.blade.php
- resources/views/donation/index.blade.php
- resources/views/donation/show.blade.php
View /donation and /donation/show
> First Attempt styling donations index and show 

- app/Http/Controllers/DonationController.php
- resources/views/donation/create.blade.php
View /donation/create to create new donation
Also hardcoded user_id in DonationController
> Improved donation create form, fixed user id

- app/Http/Controllers/BusinessController.php
- resources/views/businesses/index.blade.php
defined title in business controller
> Defined Title 

- app/Http/Controllers/TestimonialController.php
- app/Models/Testimonial.php
- app/View/Components/TestimonialCard.php
- database/factories/TestimonialFactory.php
- database/migrations/2025_03_07_000006_create_testimonials_table.php
- database/seeders/TestimonialSeeder.php
- resources/views/components/fund-fairy-header.blade.php
- resources/views/components/testimonial-card.blade.php
- resources/views/testimonial/create.blade.php
- resources/views/testimonial/index.blade.php
Also, added testimonial_image in factory, seeder, controller and model since we decided to have a user image in the testimonial
> created Testimonial card, edited index, create view, 

- app/Http/Controllers/BusinessReviewController.php
- app/View/Components/BusinessReviewCard.php
- database/seeders/BusinessReviewSeeder.php
- resources/views/business-review/index.blade.php
- resources/views/components/business-review-card.blade.php
/business-review you can see all the business reviews
> created business-review card, updated index and fixed the seeder

- app/Models/Donation.php
- resources/views/components/fund-fairy-donation-card.blade.php
- resources/views/donation/index.blade.php
View /donation to see formatting updates to table
Changes to donation card will be seen in individual donation request page
> Updated donation table and card

- app/View/Components/BusinessCard.php
- resources/views/components/business-card.blade.php
> Business Card Anton

- app/Http/Controllers/BusinessController.php
- resources/views/businesses/index.blade.php
currently getting error about business card, haven't merged business card yet so I would presume that is the cause.
> Anton 0328 show businesses

- resources/views/businesses/index.blade.php
adjusted to fund-fairy-bottom-banner
> Anton 0404 show businesses

- app/Http/Controllers/BlogPostsController.php
- app/Http/Controllers/HomeController.php
- app/Models/BlogPost.php
- app/View/Components/BlogPostCard.php
- resources/views/blog-posts/index.blade.php
- resources/views/blog-posts/show.blade.php
- resources/views/components/blog-post-card.blade.php
- resources/views/pages/index.blade.php
created blogpost html and card and show all blogpost
> michelle0328A

- app/Http/Controllers/TestimonialController.php
- resources/views/components/alert.blade.php
- resources/views/components/testimonial-card.blade.php
- resources/views/layouts/fund-fairy-layout.blade.php
- resources/views/testimonial/create.blade.php
- resources/views/testimonial/edit.blade.php
- resources/views/testimonial/index.blade.php
, testimonial card and controller
> created edit view, updated create, index, alert, layout

- app/Http/Controllers/BlogPostsController.php
- app/Models/BlogPost.php
- resources/views/components/blog-post-card.blade.php
I added author and date. On blog page only show published posts.
> michelle0404

- app/Http/Controllers/BusinessController.php
- resources/views/businesses/show.blade.php
- resources/views/components/business-card.blade.php
adjustments include....
in business card:
1: featured badge alongside featured businesses.
2: featured is given priority and ordered first over regular businesses.
in business details: 
1: rating now shows as readonly stars.
> Made requested adjustments to business card and details

- resources/views/components/fund-fairy-hero.blade.php
- resources/views/layouts/fund-fairy-layout.blade.php
View index in mobile view to see updated mobile hero section
> Updated hero section for mobile

- app/Http/Controllers/BusinessController.php
- app/Models/Business.php
- resources/views/businesses/create.blade.php
- resources/views/businesses/index.blade.php
- resources/views/businesses/show.blade.php
- removed duplicated bottom banner 
- added routing from details back to businesses
> Made further adjustments to business page

- resources/views/businesses/show.blade.php
> Changed Arrow

- app/Http/Controllers/DonationController.php
- app/Models/Donation.php
- resources/views/components/donation-request-card.blade.php
- resources/views/donation/create.blade.php
- resources/views/donation/index.blade.php
- routes/web.php
Login and create new donation on donation request page. Visit /donation to edit and delete only if it is your donation.
> Fixing donation create and edit/delete authorization

- app/Http/Controllers/BusinessController.php
- resources/views/businesses/edit.blade.php
- resources/views/businesses/show.blade.php
> Edit and Delete Functionality

- app/Http/Controllers/DonationRequestController.php
- app/Models/DonationRequest.php
- resources/views/components/fund-fairy-donation-card.blade.php
- resources/views/dashboard/index.blade.php
- resources/views/donation-request/show.blade.php
- routes/web.php
individual requests should now show when view details is clicked. Needs some formatting
> donation request show

- resources/views/auth/login.blade.php
- resources/views/auth/register.blade.php
- resources/views/components/fund-fairy-hero.blade.php
View index to see hero buttons
- Hover colors corrected
- Buttons go to correct pages
- Sign up button is hidden if signed in
View /login and /register to see buttons
- Background and hover colors corrected
> Fixed some button styling

- app/Http/Controllers/DonationController.php
- app/Http/Controllers/DonationRequestController.php
- resources/views/components/comment-card.blade.php
- resources/views/components/fund-fairy-donation-card.blade.php
- resources/views/components/fund-fairy-hero.blade.php
- resources/views/donation-request/show.blade.php
View individual donation request page to see listed donations
Click the create button to donate and be redirected back to the donation request page 
View /donation-request/3 to see pagination
> Donations on Request Page

- resources/views/components/alert.blade.php
- resources/views/testimonial/index.blade.php
> changed alert text color to white

- resources/views/components/testimonial-card.blade.php
and  made testimonial card same sizes
> Anonymous will display for users without names 

- resources/views/components/fund-fairy-header.blade.php
> Remove testimonials, bookmarks, blog posts from nav bar

- app/Http/Controllers/BusinessController.php
- resources/views/businesses/index.blade.php
pagination added to business page
> pagination added

- app/Http/Controllers/DonationController.php
> Changed donation/create page title

- app/Http/Controllers/DonationController.php
- app/Http/Controllers/DonationRequestController.php
- resources/views/donation-request/index.blade.php
- resources/views/donation-request/show.blade.php
- resources/views/vendor/pagination/tailwind.blade.php
Added pagination to comments and donation requests index
Added some more hover styling to pagination file
> More pagination

- app/Http/Controllers/BlogPostsController.php
- app/Http/Controllers/BusinessController.php
- app/Http/Controllers/BusinessReviewController.php
- app/Http/Controllers/DashboardController.php
- app/Http/Controllers/DonationRequestController.php
- app/Http/Controllers/LoginController.php
- app/Http/Controllers/NewsletterController.php
- app/Http/Controllers/RegisterController.php
- app/Http/Controllers/TestimonialController.php
- app/View/Components/PageTitle.php
- resources/views/auth/login.blade.php
- resources/views/auth/register.blade.php
- resources/views/blog-posts/index.blade.php
- resources/views/blog-posts/show.blade.php
- resources/views/business-review/index.blade.php
- resources/views/businesses/index.blade.php
- resources/views/businesses/show.blade.php
- resources/views/components/page-title.blade.php
- resources/views/dashboard/index.blade.php
- resources/views/donation-request/index.blade.php
- resources/views/donation-request/show.blade.php
- resources/views/pages/about.blade.php
- resources/views/pages/index.blade.php
- resources/views/pages/newsletter.blade.php
- resources/views/pages/privacypolicy.blade.php
- resources/views/testimonial/index.blade.php
Made page title component
Consistent heading styles (for index pages)
Consistent page title in tab slot (for index pages)
> Page Title Consistency

- app/Http/Controllers/HomeController.php
- resources/views/layouts/fund-fairy-layout.blade.php
- resources/views/pages/index.blade.php
for the second version, I kept the testimonial cards on the homepage the same as the ones in the full testimonials page
> Testimonials in homepage(second version)

- app/Http/Controllers/BusinessController.php
- resources/views/businesses/show.blade.php
- Create/Edit will route to individual business instead of ALL businesses.
> 0425 business routing anton

- app/Models/User.php
- resources/views/components/business-card.blade.php
- resources/views/components/donation-request-card.blade.php
- resources/views/components/fund-fairy-bottom-banner.blade.php
- resources/views/components/fund-fairy-donation-card.blade.php
- resources/views/components/fund-fairy-header.blade.php
- resources/views/donation-request/index.blade.php
- resources/views/layouts/fund-fairy-layout.blade.php
! Note: removed HasRoles from User because it was causing an error, reinclude if needed
Fixed some nav bar problems (not finding js error, logout link, mobile menu items)
Improved responsiveness for donation request cards and donation icon
Added colors and consistent heights to business cards
> Styling and Responsiveness Fixes

- app/Http/Controllers/DonationRequestController.php
- resources/views/donation-request/create.blade.php
Styling and made sure it works
> Donation Request Create Form
